## 1. Import necessary libraries

In [1]:
#importing liabrary
import pandas as pd

## 2. Import data

In [2]:
#importing the data
weather_report = pd.read_csv('data_clean.csv') # Yearwise weather report
weather_report.head(50)

    Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0            1   41.0    190.0   7.4     67     5    1  2010    67       S
1            2   36.0    118.0   8.0     72     5    2  2010    72       C
2            3   12.0    149.0  12.6     74     5    3  2010    74      PS
3            4   18.0    313.0  11.5     62     5    4  2010    62       S
4            5    NaN      NaN  14.3     56     5    5  2010    56       S
5            6   28.0      NaN  14.9     66     5    6  2010    66       C
6            7   23.0    299.0   8.6     65     5    7  2010    65      PS
7            8   19.0     99.0  13.8     59     5    8  2010    59       C
8            9    8.0     19.0  20.1     61     5    9  2010    61      PS
9           10    NaN    194.0   8.6     69     5   10  2010    69       S
10          11    7.0      NaN   6.9      C     5   11  2010    74       C
11          12   16.0    256.0   9.7     69     5   12  2010    69      PS
12          13   11.0    290.0   9.2     66     5   13  2010    66       S
13          14   14.0    274.0  10.9     68     5   14  2010    68       S
14          15   18.0     65.0  13.2     58     5   15  2010    58       C
15          16   14.0    334.0  11.5     64     5   16  2010    64       S
16          17   34.0    307.0  12.0     66     5   17  2010    66       S
17          18    6.0     78.0  18.4     57     5   18  2010    57       C
18          19   30.0    322.0  11.5     68     5   19  2010    68      PS
19          20   11.0     44.0   9.7     62     5   20  2010    62       S
20          21    1.0      8.0   9.7     59     5   21  2010    59       S
21          22   11.0    320.0  16.6     73     5   22  2010    73       C
22          23    4.0     25.0   9.7     61     5   23  2010    61      PS
23          24   32.0     92.0  12.0     61   May   24  2010    61       C
24          25    NaN     66.0  16.6     57     5   25  2010    57      PS
25          26    NaN    266.0  14.9     58     5   26  2010    58       C
26          27    NaN      NaN   8.0     57     5   27  2010    57      PS
27          28   23.0     13.0  12.0     67     5   28  2010    67       S
28          29   45.0    252.0  14.9     81     5   29  2010    81       S
29          30  115.0    223.0   5.7     79     5   30  2010    79       C
30          31   37.0    279.0   7.4     76     5   31  2010    76      PS
31          32    NaN    286.0   8.6     78     6    1  2010    78       S
32          33    NaN    287.0   9.7     74     6    2  2010    74       C
33          34    NaN    242.0  16.1     67     6    3  2010    67      PS
34          35    NaN    186.0   9.2     84     6    4  2010    84       C
35          36    NaN    220.0   8.6     85     6    5  2010    85      PS
36          37    NaN    264.0  14.3     79     6    6  2010    79       C
37          38   29.0    127.0   9.7     82     6    7  2010    82      PS
38          39    NaN    273.0   6.9     87     6    8  2010    87       S
39          40   71.0    291.0  13.8     90     6    9  2010    90       S
40          41   39.0    323.0  11.5     87     6   10  2010    87       S
41          42    NaN    259.0  10.9     93     6   11  2010    93       C
42          43    NaN    250.0   9.2     92     6   12  2010    92      PS
43          44   23.0    148.0   8.0     82     6   13  2010    82       S
44          45    NaN    332.0  13.8     80     6   14  2010    80       S
45          46    NaN    322.0  11.5     79     6   15  2010    79       C
46          47   21.0    191.0  14.9     77     6   16  2010    77      PS
47          48   37.0    284.0  20.7     72     6   17  2010    72       C
48          49   20.0     37.0   9.2     65     6   18  2010    65      PS
49          50   12.0    120.0  11.5     73     6   19  2010    73       S

## 3. Initial Investigation/Data Understanding

In [3]:
weather_report.dtypes

Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object

In [4]:
#checking null values 
weather_report.isnull().sum()

Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

In [5]:
weather_report.shape

(158, 10)

## 4. Data Preparation/Preprocessing

* Data Cleaning - dropna, mean, median, mode Imputation, replace
* Data Transformation
        -  If data is continous - Standardization/Normalization, MinMaxScaler
        -  If data is discrete  - Label Encoding, One Hot Encoding
* Datatype Conversation - ie, from Object to int or float or datetime

In [6]:
#Dropping Unnamed: 0 and Ozone column
weather_report.drop(labels=['Unnamed: 0','Ozone'],axis=1,inplace=True)
weather_report

     Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0      190.0   7.4     67     5    1  2010    67       S
1      118.0   8.0     72     5    2  2010    72       C
2      149.0  12.6     74     5    3  2010    74      PS
3      313.0  11.5     62     5    4  2010    62       S
4        NaN  14.3     56     5    5  2010    56       S
..       ...   ...    ...   ...  ...   ...   ...     ...
153    190.0   7.4     67     5    1  2010    67       C
154    193.0   6.9     70     9   26  2010    70      PS
155    145.0  13.2     77     9   27  2010    77       S
156    191.0  14.3     75     9   28  2010    75       S
157    131.0   8.0     76     9   29  2010    76       C

[158 rows x 8 columns]

In [7]:
weather_report.isnull().sum()

Solar.R    7
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [8]:
weather_report.describe(include = 'all')

,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [9]:
#checking median of Solar.R
weather_report['Solar.R'].median()

197.0

In [10]:
#filling nan values by median
weather_report['Solar.R'] = weather_report['Solar.R'].fillna(value=weather_report['Solar.R'].median(), axis=0)

In [11]:
weather_report.isnull().sum()

Solar.R    0
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [12]:
weather_report.dtypes

Solar.R    float64
Wind       float64
Temp C      object
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [13]:
#converting the data types 
weather_report['Temp C'] = pd.to_numeric(weather_report['Temp C'], errors='coerce')
weather_report['Month']  = pd.to_numeric(weather_report['Month'], errors='coerce')

In [14]:
weather_report.head(50)

    Solar.R  Wind  Temp C  Month  Day  Year  Temp Weather
0     190.0   7.4    67.0    5.0    1  2010    67       S
1     118.0   8.0    72.0    5.0    2  2010    72       C
2     149.0  12.6    74.0    5.0    3  2010    74      PS
3     313.0  11.5    62.0    5.0    4  2010    62       S
4     197.0  14.3    56.0    5.0    5  2010    56       S
5     197.0  14.9    66.0    5.0    6  2010    66       C
6     299.0   8.6    65.0    5.0    7  2010    65      PS
7      99.0  13.8    59.0    5.0    8  2010    59       C
8      19.0  20.1    61.0    5.0    9  2010    61      PS
9     194.0   8.6    69.0    5.0   10  2010    69       S
10    197.0   6.9     NaN    5.0   11  2010    74       C
11    256.0   9.7    69.0    5.0   12  2010    69      PS
12    290.0   9.2    66.0    5.0   13  2010    66       S
13    274.0  10.9    68.0    5.0   14  2010    68       S
14     65.0  13.2    58.0    5.0   15  2010    58       C
15    334.0  11.5    64.0    5.0   16  2010    64       S
16    307.0  12.0    66.0    5.0   17  2010    66       S
17     78.0  18.4    57.0    5.0   18  2010    57       C
18    322.0  11.5    68.0    5.0   19  2010    68      PS
19     44.0   9.7    62.0    5.0   20  2010    62       S
20      8.0   9.7    59.0    5.0   21  2010    59       S
21    320.0  16.6    73.0    5.0   22  2010    73       C
22     25.0   9.7    61.0    5.0   23  2010    61      PS
23     92.0  12.0    61.0    NaN   24  2010    61       C
24     66.0  16.6    57.0    5.0   25  2010    57      PS
25    266.0  14.9    58.0    5.0   26  2010    58       C
26    197.0   8.0    57.0    5.0   27  2010    57      PS
27     13.0  12.0    67.0    5.0   28  2010    67       S
28    252.0  14.9    81.0    5.0   29  2010    81       S
29    223.0   5.7    79.0    5.0   30  2010    79       C
30    279.0   7.4    76.0    5.0   31  2010    76      PS
31    286.0   8.6    78.0    6.0    1  2010    78       S
32    287.0   9.7    74.0    6.0    2  2010    74       C
33    242.0  16.1    67.0    6.0    3  2010    67      PS
34    186.0   9.2    84.0    6.0    4  2010    84       C
35    220.0   8.6    85.0    6.0    5  2010    85      PS
36    264.0  14.3    79.0    6.0    6  2010    79       C
37    127.0   9.7    82.0    6.0    7  2010    82      PS
38    273.0   6.9    87.0    6.0    8  2010    87       S
39    291.0  13.8    90.0    6.0    9  2010    90       S
40    323.0  11.5    87.0    6.0   10  2010    87       S
41    259.0  10.9    93.0    6.0   11  2010    93       C
42    250.0   9.2    92.0    6.0   12  2010    92      PS
43    148.0   8.0    82.0    6.0   13  2010    82       S
44    332.0  13.8    80.0    6.0   14  2010    80       S
45    322.0  11.5    79.0    6.0   15  2010    79       C
46    191.0  14.9    77.0    6.0   16  2010    77      PS
47    284.0  20.7    72.0    6.0   17  2010    72       C
48     37.0   9.2    65.0    6.0   18  2010    65      PS
49    120.0  11.5    73.0    6.0   19  2010    73       S

In [15]:
#describing the all values
weather_report.describe()

,Solar.R,Wind,Temp C,Month,Day,Year,Temp
count,158.000000,158.000000,157.000000,157.000000,158.000000,158.0,158.000000
mean,185.917722,9.957595,77.751592,7.044586,16.006329,2010.0,77.727848
std,86.755676,3.511261,9.403120,1.433768,8.997166,0.0,9.377877
min,7.000000,1.700000,56.000000,5.000000,1.000000,2010.0,56.000000
25%,127.000000,7.400000,72.000000,6.000000,8.000000,2010.0,72.000000
50%,197.000000,9.700000,79.000000,7.000000,16.000000,2010.0,78.500000
75%,255.000000,11.875000,84.000000,8.000000,24.000000,2010.0,84.000000
max,334.000000,20.700000,97.000000,9.000000,31.000000,2010.0,97.000000

In [16]:
#checking mean of Temp C
weather_report['Temp C'].mean()

77.7515923566879

In [17]:
#filling nan values by mean
weather_report['Temp C'] = weather_report['Temp C'].fillna(value=weather_report['Temp C'].mean(),axis=0)

In [18]:
#filling nan values in month column
weather_report['Month'] = weather_report['Month'].fillna(value=5,axis=0)

In [19]:
weather_report.head(50)

    Solar.R  Wind     Temp C  Month  Day  Year  Temp Weather
0     190.0   7.4  67.000000    5.0    1  2010    67       S
1     118.0   8.0  72.000000    5.0    2  2010    72       C
2     149.0  12.6  74.000000    5.0    3  2010    74      PS
3     313.0  11.5  62.000000    5.0    4  2010    62       S
4     197.0  14.3  56.000000    5.0    5  2010    56       S
5     197.0  14.9  66.000000    5.0    6  2010    66       C
6     299.0   8.6  65.000000    5.0    7  2010    65      PS
7      99.0  13.8  59.000000    5.0    8  2010    59       C
8      19.0  20.1  61.000000    5.0    9  2010    61      PS
9     194.0   8.6  69.000000    5.0   10  2010    69       S
10    197.0   6.9  77.751592    5.0   11  2010    74       C
11    256.0   9.7  69.000000    5.0   12  2010    69      PS
12    290.0   9.2  66.000000    5.0   13  2010    66       S
13    274.0  10.9  68.000000    5.0   14  2010    68       S
14     65.0  13.2  58.000000    5.0   15  2010    58       C
15    334.0  11.5  64.000000    5.0   16  2010    64       S
16    307.0  12.0  66.000000    5.0   17  2010    66       S
17     78.0  18.4  57.000000    5.0   18  2010    57       C
18    322.0  11.5  68.000000    5.0   19  2010    68      PS
19     44.0   9.7  62.000000    5.0   20  2010    62       S
20      8.0   9.7  59.000000    5.0   21  2010    59       S
21    320.0  16.6  73.000000    5.0   22  2010    73       C
22     25.0   9.7  61.000000    5.0   23  2010    61      PS
23     92.0  12.0  61.000000    5.0   24  2010    61       C
24     66.0  16.6  57.000000    5.0   25  2010    57      PS
25    266.0  14.9  58.000000    5.0   26  2010    58       C
26    197.0   8.0  57.000000    5.0   27  2010    57      PS
27     13.0  12.0  67.000000    5.0   28  2010    67       S
28    252.0  14.9  81.000000    5.0   29  2010    81       S
29    223.0   5.7  79.000000    5.0   30  2010    79       C
30    279.0   7.4  76.000000    5.0   31  2010    76      PS
31    286.0   8.6  78.000000    6.0    1  2010    78       S
32    287.0   9.7  74.000000    6.0    2  2010    74       C
33    242.0  16.1  67.000000    6.0    3  2010    67      PS
34    186.0   9.2  84.000000    6.0    4  2010    84       C
35    220.0   8.6  85.000000    6.0    5  2010    85      PS
36    264.0  14.3  79.000000    6.0    6  2010    79       C
37    127.0   9.7  82.000000    6.0    7  2010    82      PS
38    273.0   6.9  87.000000    6.0    8  2010    87       S
39    291.0  13.8  90.000000    6.0    9  2010    90       S
40    323.0  11.5  87.000000    6.0   10  2010    87       S
41    259.0  10.9  93.000000    6.0   11  2010    93       C
42    250.0   9.2  92.000000    6.0   12  2010    92      PS
43    148.0   8.0  82.000000    6.0   13  2010    82       S
44    332.0  13.8  80.000000    6.0   14  2010    80       S
45    322.0  11.5  79.000000    6.0   15  2010    79       C
46    191.0  14.9  77.000000    6.0   16  2010    77      PS
47    284.0  20.7  72.000000    6.0   17  2010    72       C
48     37.0   9.2  65.000000    6.0   18  2010    65      PS
49    120.0  11.5  73.000000    6.0   19  2010    73       S

In [20]:
#checking data types
weather_report.dtypes

Solar.R    float64
Wind       float64
Temp C     float64
Month      float64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [21]:
#checking null values
weather_report.isnull().sum()

Solar.R    0
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [22]:
#converting float into integer
weather_report.Month = weather_report.Month.astype('int')

In [23]:
#checking data types
weather_report.dtypes

Solar.R    float64
Wind       float64
Temp C     float64
Month        int32
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [24]:
#describing the all values 
weather_report.describe(include = 'all')

,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,59
mean,185.917722,9.957595,77.751592,7.031646,16.006329,2010.0,77.727848,NaN
std,86.755676,3.511261,9.373126,1.438421,8.997166,0.0,9.377877,NaN
min,7.000000,1.700000,56.000000,5.000000,1.000000,2010.0,56.000000,NaN
25%,127.000000,7.400000,72.000000,6.000000,8.000000,2010.0,72.000000,NaN
50%,197.000000,9.700000,78.500000,7.000000,16.000000,2010.0,78.500000,NaN
75%,255.000000,11.875000,84.000000,8.000000,24.000000,2010.0,84.000000,NaN
max,334.000000,20.700000,97.000000,9.000000,31.000000,2010.0,97.000000,NaN

In [25]:
#checking unique values
weather_report.Weather.unique()

array(['S', 'C', 'PS', nan], dtype=object)

In [26]:
#checking mode of target
weather_report.Weather.mode()[0]

'S'

In [27]:
#filling null values by mean
weather_report['Weather'] = weather_report['Weather'].fillna(value=weather_report.Weather.mode()[0],axis=0)

In [28]:
#checking null values
weather_report.isnull().sum()

Solar.R    0
Wind       0
Temp C     0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [29]:
#importing Onehot Encoding and Label Encoding for converting categorical into numeric
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le = LabelEncoder()
weather_report['Weather'] = le.fit_transform(weather_report['Weather'])

In [30]:
#reading first fifty record
weather_report.head(50)

    Solar.R  Wind     Temp C  Month  Day  Year  Temp  Weather
0     190.0   7.4  67.000000      5    1  2010    67        2
1     118.0   8.0  72.000000      5    2  2010    72        0
2     149.0  12.6  74.000000      5    3  2010    74        1
3     313.0  11.5  62.000000      5    4  2010    62        2
4     197.0  14.3  56.000000      5    5  2010    56        2
5     197.0  14.9  66.000000      5    6  2010    66        0
6     299.0   8.6  65.000000      5    7  2010    65        1
7      99.0  13.8  59.000000      5    8  2010    59        0
8      19.0  20.1  61.000000      5    9  2010    61        1
9     194.0   8.6  69.000000      5   10  2010    69        2
10    197.0   6.9  77.751592      5   11  2010    74        0
11    256.0   9.7  69.000000      5   12  2010    69        1
12    290.0   9.2  66.000000      5   13  2010    66        2
13    274.0  10.9  68.000000      5   14  2010    68        2
14     65.0  13.2  58.000000      5   15  2010    58        0
15    334.0  11.5  64.000000      5   16  2010    64        2
16    307.0  12.0  66.000000      5   17  2010    66        2
17     78.0  18.4  57.000000      5   18  2010    57        0
18    322.0  11.5  68.000000      5   19  2010    68        1
19     44.0   9.7  62.000000      5   20  2010    62        2
20      8.0   9.7  59.000000      5   21  2010    59        2
21    320.0  16.6  73.000000      5   22  2010    73        0
22     25.0   9.7  61.000000      5   23  2010    61        1
23     92.0  12.0  61.000000      5   24  2010    61        0
24     66.0  16.6  57.000000      5   25  2010    57        1
25    266.0  14.9  58.000000      5   26  2010    58        0
26    197.0   8.0  57.000000      5   27  2010    57        1
27     13.0  12.0  67.000000      5   28  2010    67        2
28    252.0  14.9  81.000000      5   29  2010    81        2
29    223.0   5.7  79.000000      5   30  2010    79        0
30    279.0   7.4  76.000000      5   31  2010    76        1
31    286.0   8.6  78.000000      6    1  2010    78        2
32    287.0   9.7  74.000000      6    2  2010    74        0
33    242.0  16.1  67.000000      6    3  2010    67        1
34    186.0   9.2  84.000000      6    4  2010    84        0
35    220.0   8.6  85.000000      6    5  2010    85        1
36    264.0  14.3  79.000000      6    6  2010    79        0
37    127.0   9.7  82.000000      6    7  2010    82        1
38    273.0   6.9  87.000000      6    8  2010    87        2
39    291.0  13.8  90.000000      6    9  2010    90        2
40    323.0  11.5  87.000000      6   10  2010    87        2
41    259.0  10.9  93.000000      6   11  2010    93        0
42    250.0   9.2  92.000000      6   12  2010    92        1
43    148.0   8.0  82.000000      6   13  2010    82        2
44    332.0  13.8  80.000000      6   14  2010    80        2
45    322.0  11.5  79.000000      6   15  2010    79        0
46    191.0  14.9  77.000000      6   16  2010    77        1
47    284.0  20.7  72.000000      6   17  2010    72        0
48     37.0   9.2  65.000000      6   18  2010    65        1
49    120.0  11.5  73.000000      6   19  2010    73        2

### >>>>>>>>>>>>>>>>>>>>>>>> Data Cleaning Completed <<<<<<<<<<<<<<<<<<<<<<<<<<<<<